[package]
name = "gon"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1.3"
hyper = { version = "1.7.0", features = ["full"] }
hyper-util = { version = "0.1", featues = ["tokio"], features = ["tokio"] }
tokio = { version = "1.48.0", features = ["full"] }
